### ISSUE TITLE
Use vis-lspc without lua-lpeg compiled into vis

### ISSUE THREAD

**Issue by jgarte** [fischerling/vis-lspc#20]
Is it possible to use `vis-lspc` _without__ lua-lpeg syntax highlighting support?

**Comment by jgarte** [comment]
I currently get the following error when running `lspc-start-server lua`

```
LSPC Error: No syntax provided
```

**Comment by jgarte** [comment]
Is `vis-lspc` dependent on `lua-lpeg` or can that error message be softened to allow language server protocol support without lpeg lexers?

I think this would be a cool feature to add :)

**Comment by fischerling** [comment]
> I currently get the following error when running `lspc-start-server lua`
> 
> ```
> LSPC Error: No syntax provided
> ```
> 
> I have the `lua-language-server` binary in `PATH`.

I am currently not familiar enough with vis internals to tell if lua-lpeg is needed to use vis-lspc.
But I would imagine vis-lspc does not need lua-lpeg.

But it uses the syntax variable set by vis to determine which language server to start/talk to.
And vis uses lua-lpeg to do its syntax highlighting so maybe it does not set
the syntax variable without lua-lpeg support because it could not do highlighting
anyway.

When setting the syntax using `:set syntax <syntax>` before starting the language server
using `:lspc-start-server <syntax>` it should work without lua-lpeg.

I could seeing setting the syntax variable on the current file when manually starting
a language server.

Do you think this "feature" would be beneficial?

**Comment by jgarte** [comment]
> I could seeing setting the syntax variable on the current file when manually starting
a language server. 

Would that still depend of lpeg?

> Do you think this "feature" would be beneficial?

I think it might be nice to set language servers in a file that are decoupled from the syntax highlighters.

Not that I want to set incorrect language servers on a file but if I want to use lsp without syntax highlighting enabled then
that might be a cool feature for vis-lspc for the acme inspired users.

I think it also depends on how much complexity this introduces. I too, would like to have a minimal codebase.

I'm intending to rewrite the lexers in vis to only highlight comments and strings.

Unrelated, I started configuring vis with [fennel](https://fennel-lang.org/):

https://git.sr.ht/~jgart/dotfiles/tree/master/item/private_dot_config/vis

I also added a wiki entry on how to set up fennel with vis:

https://github.com/martanne/vis/wiki/Tips-and-Tricks#how-can-i-use-fennel-to-configure-vis

There's one bug at the moment with it that I'm trying to catch:

It works if you're in ~/.config/vis/ but once you cd elsewhere it fails to find the fennel config :)

**Comment by jgarte** [comment]
> Do you think this "feature" would be beneficial?

I think it would be beneficial to be able to start a language server without having to worry about the syntax that is currently enabled in a buffer.

The above, for example, blocked me from using the [rnix](https://github.com/nix-community/rnix-lsp) language server. Since vis did not have an lpeg or file type defined for nix language I could not turn on the language server until I make one.

I sometimes code with syntax highlighting disabled and would like to just turn on a language server on a file.

**Comment by fischerling** [comment]
Moved to [https://gitlab.com/muhq/vis-lspc/-/issues/20](https://gitlab.com/muhq/vis-lspc/-/issues/20).
